spring:
  datasource:
    #    url: jdbc:h2:tcp://localhost/~/springbootjpa
    #    username: sa
    #    password:
    #    driver-class-name: org.h2.Driver
    url: jdbc:mariadb://localhost:3306/springboot-jpa
    username: sbj
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        # show_sql: true, system out 에 출력
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

logging:
  level:
    org.hibernate.SQL: debug # 로그를 통해 출력
    org.hibernate.orm.jdbc.bind: trace
# org.hibernate.type: trace #스프링 부트 2.x, hibernate5
# org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6